config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  root 'tweets#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :messeage,length:{in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    messeage = params[:tweet][:messeage]
    tdate = Time.current
    @tweet = Tweet.new(messeage: messeage, tdate: tdate)
    if @tweet.save
      flash[:notice] = '投稿しました'
      redirect_to '/'
    else
      render 'new'
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to '/'
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    messeage = params[:tweet][:messeage]
    @tweet.update(messeage: messeage)
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="container">
    <div id="header">
      <%= render "header" %>
    </div>
    <div id="sidebar">
      <%= render "sidebar" %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
    <div id="footer">
      <%= render "footer" %>
    </div>
  </div>
</body>
</html>

app/views/tweets/_footer.html.erb
<footer>
<p>CopyRight&copy;1611140062 All rights reserved.</p>
</footer>

app/views/tweets/_form.html.erb
<p><%= f.label :messeage,'ツイート' %>
<%= f.text_area :messeage, size: "100x20" %>
<%= f.submit 'ツイート' ,{:class => "tweet_btn" }%></p>

app/views/tweets/_header.html.erb
<%= link_to 'ホーム', tweets_path,{ :class => "header_btn" } %>
<%= link_to 'モーメント', 'hoge',{ :class => "header_btn" } %>
<%= link_to '通知', 'null',{ :class => "header_btn" } %>
<%= link_to 'メッセージ', 'fuga',{ :class => "header_btn" } %>

app/views/tweets/_sidebar.html.erb
<div id="username">
  <h2>Username</h2>
  <h4>@usermane</h4>
</div>
<div id="userintro">
  <p>ここに自己紹介</p>
  <h4>所在地</h4>
  <h4>ホームページ</h4>
  <h4>登録日</h4>
</div>

app/views/tweets/_tweetbtn.html.erb
<%= link_to 'ツイート', { :controller => "tweets", :action => "new"}, { :class => "tweet_btn" } %>

app/views/tweets/edit.html.erb
<%= form_for @tweet, url: {action: :update} do|f| %>
  <%= render "form",f: f %>
<% end %>

app/views/tweets/index.html.erb
<% flash.each do |type, msg| %>
<%= msg %>
<% end %>
<%= render "tweetbtn" %>

<div id="timeline">
<table border="1">

<% @tweets.each do |tweet| %>
<tr>
  <td height="100"><img src="noimage.png", class="img_icon"><h3>username</h3><h5>@username&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= ((Time.current - tweet.tdate)/60).to_i %>分前</h5><%= link_to tweet.messeage, tweet_path(tweet.id) %></td>
</tr>
<tr>
  <td align="right">
  <%= link_to '編集', edit_tweet_path(tweet.id) %>
  <%= link_to '削除', tweet_path(tweet.id), method: :delete %>
  </td>
</tr>
<% end %>
</table>
</div>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
    <% @tweet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>
<%= form_for @tweet, url: {action: :create} do|f| %>
  <%= render "form", f: f %>
<% end %>

app/views/tweets/show.html.erb
<%= render "tweetbtn" %>
<p><%= @tweet.messeage %>
<%= ((Time.current - @tweet.tdate)/60).to_i %>分前</p>
<%= link_to '戻る', "/" %>